import { useEffect, useState } from "react";
import { api, brl, dateTimeBR } from "../lib/api";
import { Modal } from "../components/Modal";
import { Badge, EmptyState, Field, Loading, PageHeader } from "../components/UI";

const labels: Record<string, string> = { purchase: "Compra", consumption: "Consumo", return: "Devolução", opening: "Saldo inicial", adjustment_in: "Ajuste +", adjustment_out: "Ajuste -" };
export function StockPage() {
  const [items, setItems] = useState<any[]>([]); const [materials, setMaterials] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [form, setForm] = useState({ material_id: "", quantity: 0, notes: "" });
  const load = async () => { setLoading(true); try { const [movements, materialData] = await Promise.all([api<{ items: any[] }>("/stock/movements"), api<{ items: any[] }>("/materials")]); setItems(movements.items); setMaterials(materialData.items); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); await api("/stock/adjust", { method: "POST", body: JSON.stringify(form) }); setOpen(false); await load(); };
  return <><PageHeader eyebrow="MOVIMENTAÇÃO DE MATERIAIS" title="Consumo, baixas e ajustes" description="Auditoria completa das entradas e saídas. Consumos de pedidos são confirmados na própria OS." action={<button className="primary-button" onClick={() => { setForm({ material_id: materials[0]?.id || "", quantity: 0, notes: "" }); setOpen(true); }}>+ Ajuste manual</button>} />
    <div className="panel table-panel">{loading ? <Loading /> : items.length === 0 ? <EmptyState title="Nenhuma movimentação" text="As compras, baixas e ajustes aparecerão aqui." /> : <div className="table-wrap"><table><thead><tr><th>Data</th><th>Material</th><th>Tipo</th><th>Quantidade</th><th>Custo</th><th>Pedido / Compra</th><th>Usuário</th><th>Observação</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{dateTimeBR(item.created_at)}</td><td><strong>{item.material_name}</strong></td><td><Badge tone={Number(item.quantity) < 0 ? "danger" : "success"}>{labels[item.type] || item.type}</Badge></td><td className={Number(item.quantity) < 0 ? "text-red" : "text-green"}>{Number(item.quantity) > 0 ? "+" : ""}{item.quantity} {item.unit}</td><td>{brl(Math.abs(Number(item.total_cost)))}</td><td>{item.order_code || item.purchase_code || "—"}</td><td>{item.user_name || "—"}</td><td>{item.notes || "—"}</td></tr>)}</tbody></table></div>}</div>
    {open && <Modal title="Ajuste manual de estoque" onClose={() => setOpen(false)}><form className="form-grid" onSubmit={save}><Field label="Material" wide><select value={form.material_id} onChange={(event) => setForm({ ...form, material_id: event.target.value })}>{materials.map((material) => <option key={material.id} value={material.id}>{material.name} — saldo {material.current_stock} {material.unit}</option>)}</select></Field><Field label="Quantidade"><input type="number" step="0.001" value={form.quantity} onChange={(event) => setForm({ ...form, quantity: Number(event.target.value) })} /><small>Use valor positivo para entrada e negativo para saída.</small></Field><Field label="Motivo" wide><textarea required value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></Field><div className="form-actions wide"><button type="button" className="ghost-button" onClick={() => setOpen(false)}>Cancelar</button><button className="primary-button">Confirmar ajuste</button></div></form></Modal>}
  </>;
}
